CREATE TABLE Attachment
(
 AID   int NOT NULL,
 Title text NULL,
 JID   int NOT NULL,
 AUrl   NOT NULL,
 CONSTRAINT PK_122 PRIMARY KEY ( AID ),
 CONSTRAINT FK_125 FOREIGN KEY ( JID ) REFERENCES Job ( JID )
);

CREATE INDEX FK_127 ON Attachment
(
 JID
);
